version: '2'
services:
  picker:
    build: ./picker
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
      - counter
      - counter:counter.cloud66.local

  chef:
    build: ./chef
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local

  bricksandmortar:
    build: 
      dockerfile: Dockerfile.development
      context: ./bricksandmortar
    stdin_open: true
    tty: true
    ports:
      - "8002:80"  
  #  volumes:
  #    - ${PWD}/bricksandmortar/middleman:/home/app

  accountant:
    build: ./accountant
    stdin_open: true
    tty: true
    links:
      - mysql
      - mysql:mysql.cloud66.local
    environment:
      - RACK_ENV=production
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=backery_dev
      - SECRET_KEY_BASE=232sd82934283098sd

    ports:
      - "8001:80"  
  counter:
    build: ./counter
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/counter:/home/app
    links:
      - mysql
      - mysql:mysql.cloud66.local
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
    environment:
      - RACK_ENV=production
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=backery_dev

    ports:
      - "8000:80"  
  rainbowcake:
    build: ./minions/rainbowcake
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  bagel:
    build: ./minions/bagel
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
  
  donut:
    build: ./minions/donut
    stdin_open: true
    tty: true
    links:
      - rabbitmq
      - rabbitmq:rabbitmq.cloud66.local
   # volumes:
   #   - ${PWD}/minions/donut:/home/app
    environment:
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root