version: '2'
services:
  accountant:
    build: .
    stdin_open: true
    tty: true
    links:
      - mysql
      - mysql:mysql.cloud66.local
    volumes:
      - ${PWD}:/home/app
    environment:
      - RACK_ENV=development
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8001:80"  
      
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root