---
services:
  frontend_bricksandmortar:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/bricksandmortar
    git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - www.microservice101.io
  cms_accountant:
    env_vars:
      RAILS_ENV: production
    deploy_command: bundle exec rake db:migrate
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/accountant
    git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - cms.www.microservice101.io
  counter:
    env_vars:
      RACK_ENV: production
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/counter
    git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - api.microservice101.io
  minion_spacecake:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/minions/spacecake
    git_branch: master
  minion_bagel:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/minions/bagel
    git_branch: master
  worker_chef:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/chef
    git_branch: master
  worker_picker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/picker
    git_branch: master
databases:
- mysql
- rabbitmq
