---
version: 2
services:
  #frontend
  bricksandmortar-frontend:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/bricksandmortar
    git_branch: master
    ports:
    - 80:80:443
  #cms
  accountant-cms:
    env_vars:
      RAILS_ENV: production
    deploy_command: bundle exec rake db:migrate
    build_command: bundle exec rake db:migrate
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/accountant
    git_branch: master
    ports:
    - 80:8000
  counter-api:
    env_vars:
      RACK_ENV: production
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/counter
    git_branch: master
    ports:
    - 80:8001
  spacecake-worker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/minions/spacecake
    git_branch: master
  bagel-worker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/minions/bagel
    git_branch: master
  donut-worker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/minions/donut
    git_branch: master
  chef-worker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/chef
    git_branch: master
  picker-worker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    build_root: bakery/picker
    git_branch: master
databases:
- mysql
- rabbitmq
