---
services:
  frontend:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    ports:
    - container: 80
      http: 80
      https: 443
    dockerfile_path: Dockerfile
    build_root: bakery/bricksandmortar
  cms:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    ports:
    - container: 80
      http: 8000
    dockerfile_path: Dockerfile
    deploy_command: bundle exec rake db:migrate
    env_vars:
      RAILS_ENV: production
    build_root: bakery/accountant
  api:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    ports:
    - container: 80
      http: 8001
    dockerfile_path: Dockerfile
    env_vars:
      RACK_ENV: production
    build_root: bakery/counter
  worker-baker-spacecake:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    dockerfile_path: Dockerfile
    build_root: bakery/minions/spacecake
  worker-baker-bagel:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    dockerfile_path: Dockerfile
    build_root: bakery/minions/bagel
  worker-baker-donut:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    dockerfile_path: Dockerfile
    build_root: bakery/minions/donut
  worker-chef:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    dockerfile_path: Dockerfile
    build_root: bakery/chef
  worker-order-picker:
    git_url: http://github.com/cloud66-samples/microservices_101.git
    git_branch: master
    dockerfile_path: Dockerfile
    build_root: bakery/picker
databases:
- mysql
- rabbitmq
