---
services:
  bricksandmortar:
    image: cloud66/microservices101_demo_bricksandmortar
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/bricksandmortar
    #git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - www.microservice101.io
  accountant:
    image: cloud66/microservices101_demo_accountant
    env_vars:
      RAILS_ENV: production
    deploy_command: bundle exec rake db:migrate
    build_command: bundle exec rake db:migrate
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/accountant
    #git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - cms.microservice101.io
  counter:
    image: cloud66/microservices101_demo_counter
    env_vars:
      RACK_ENV: production
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/counter
    #git_branch: master
    ports:
    - 80:80:443
    traffic_matches:
    - api.microservice101.io
  spacecake:
    image: cloud66/microservices101_demo_minion_spacecake
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/minions/spacecake
    #git_branch: master
  bagel:
    image: cloud66/microservices101_demo_minion_bagel
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/minions/bagel
    #git_branch: master
  donut:
    image: cloud66/microservices101_demo_minion_donut
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/minions/donut
    #git_branch: master
  chef:
    image: cloud66/microservices101_demo_chef
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/chef
    #git_branch: master
  picker:
   image: cloud66/microservices101_demo_picker
    #git_url: http://github.com/cloud66-samples/microservices_101.git
    #build_root: bakery/picker
    #git_branch: master
databases:
- mysql
- rabbitmq
