version: '2'
services:
  bricksandmortar:
    build: 
      context: .
      args:
        - COUNTER_ADDRESS=192.168.99.100
        - COUNTER_PORT=8000
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}/middleman:/home/app
    ports:
      - "8002:80"  
    environment:
      - COUNTER_ADDRESS=192.168.99.100
      - COUNTER_PORT=8000
   
 