development:
  adapter: mysql2
  encoding: utf8
  database: backery_dev
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'mysql.cloud66.local'  %>
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: backery_test
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'mysql.cloud66.local'  %>
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: backery_prod
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] || 'mysql.cloud66.local'  %>
  port: 3306